### ISSUE TITLE
Feature: Supports all core data types from profiles

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/crate-o#1]
- [Text](https://github.com/describo/profiles/blob/master/profile-docs/types.md#text)
- [TextArea](https://github.com/describo/profiles/blob/master/profile-docs/types.md#textarea) <-- NOT NEEDED 
- [Number](https://github.com/describo/profiles/blob/master/profile-docs/types.md#number)
- [Date, DateTime, Time](https://github.com/describo/profiles/blob/master/profile-docs/types.md#date-datetime-time)
- [Geo](https://github.com/describo/profiles/blob/master/profile-docs/types.md#geo)
- [URL](https://github.com/describo/profiles/blob/master/profile-docs/types.md#url)
- [Select, SelectURL, SelectObject](https://github.com/describo/profiles/blob/master/profile-docs/types.md#select-selecturl-selectobject) <-- SelectURL probably not needed just work with {"@id": "https://..."}
- [Value](https://github.com/describo/profiles/blob/master/profile-docs/types.md#value) <-- This is problematic -- do not implement until we have a use case

**Comment by moisbo** [comment]
Alvin Working on Maps
