### ISSUE TITLE
Create Crate-O user manual / documentation

### ISSUE THREAD

**Issue by weaver-m** [Language-Research-Technology/crate-o#106]
Feedback from Wolfgang (during work on putting the Diana Slade collection onto ONI and preparing to do the same for Sydney Speaks data):  Crate-O users need guidance, e.g. when using Bulk Add, what to watch out for in filling out the Excel ro-crate template, what are absolute required fields in Crate-O, provide clear prompts and warnings in Crate-O, etc. to successfully generate a proper ro-crate-metadata JSON file

**Comment by moisbo** [comment]
Done here: https://www.ldaca.edu.au/resources/user-guides/crate-o/
