### ISSUE TITLE
Crate-O Help doc updates

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#114]
Just three sections in the general Crate-O user guide that I either don't have a good description for or are missing other detail.

https://github.com/Language-Research-Technology/crate-o/blob/97e66f797a44b046275ecbbc1c2ea358a85a98b8/help/index.md?plain=1#L75

https://github.com/Language-Research-Technology/crate-o/blob/97e66f797a44b046275ecbbc1c2ea358a85a98b8/help/index.md?plain=1#L77
For the above, I'm not sure if we can link to this page yet since it's on the great-metadata-migration branch: https://github.com/Language-Research-Technology/ldac-profile/blob/great-metadata-migration/profile/profile.md

https://github.com/Language-Research-Technology/crate-o/blob/97e66f797a44b046275ecbbc1c2ea358a85a98b8/help/index.md?plain=1#L80

**Comment by rosanna-smith** [comment]
@ptsefton putting aside the link needed if that's not finalised yet, would you have good descriptions of Others and Create New Entity? I was also wondering what we should call the two sidebars on Crate-O - right side - Entity Sidebar?, left side - Metadata Sidebar? Not sure how accurate that is.

**Comment by ptsefton** [comment]
We probably don't want to refer to things using left / right as these may depend on the devices people view things on.

I think we should have a session where we look at the interface and label it explicitly THEN tidy up the doco.

something like:


<img width="698" alt="image" src="https://github.com/Language-Research-Technology/crate-o/assets/756184/16e0958e-7910-4156-81ff-0f343e53a33a">

**Comment by rosanna-smith** [comment]
Right - Entity Navigator
Left - Property Groups
Middle pane - Entity Properties
![Screenshot 2024-05-03 at 11 10 59 am](https://github.com/Language-Research-Technology/crate-o/assets/143474414/fe6c9897-08ec-4ede-a62b-ef60644c9d20)

**Comment by ptsefton** [comment]
@rosanna-smith the branches are confusing ATM - I might do this after @alvinsw  has merged the latest stuff
