### ISSUE TITLE
Schema mode: Allow return to root Entity after saving 

### ISSUE THREAD

**Issue by weaver-m** [Language-Research-Technology/crate-o#116]
Sample case in Mode:Schema profile 
DefinedTerm:Transcription was incorrectly assigned to DefinedTermSet:DerivedMaterialTypeTerms and then reassigned to the correct DTS:AnnotationTypeTerms. After saving the record, unable to go back to rootDataEntity Language Data Commons Schema Terms, had to restart Crate-O.

**Comment by alvinsw** [comment]
Temporarily fixed this by forcing to go to root after save.
