### ISSUE TITLE
Types for DefinedTerm and DefinedTermSet has wrong case

### ISSUE THREAD

**Issue by stain** [Language-Research-Technology/crate-o#119]
In the schema.org-schema profile, types should be CamelCase, e.g. http://schema.org/DefinedTerm and http://schema.org/DefinedTermSet but now they come as `definedTerm` and `definedTermSet` (see JSON below)

This explains why the properties for relating these types don't show up, e.g. [inDefinedTermSet](https://schema.org/inDefinedTermSet), [hasDefinedTerm](https://schema.org/hasDefinedTerm) and [termCode](https://schema.org/termCode)

```
    {
      "@id": "#terms",
      "@type": "definedTermSet",
      "name": "Set of terms"
    },
    {
      "@id": "#definedTermSet-1",
      "@type": "definedTermSet",
      "name": "definedTermSet-1"
    },
```

**Comment by ptsefton** [comment]
Not sure how to fix this in Crate-O -- where do you see an error?

**Comment by moisbo** [comment]
Check DefinedTerm capitalisation in the mode file in the ro-crate-editor-profile repo and update the description

**Comment by rosanna-smith** [comment]
Now updated at: https://github.com/Language-Research-Technology/ro-crate-editor-profiles/blob/main/modes/schema.json
