### ISSUE TITLE
Make sure pcdm hasMember and memberOf have the correct PCDM based URIs and are in the Structure input group

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/crate-o#121]

**Comment by ptsefton** [comment]
No you need to change the memberOf one as well to pcdm



--


From: otili9890 ***@***.***>
Date: Friday, 19 April 2024 at 11:08 am
To: Language-Research-Technology/crate-o ***@***.***>
Cc: Peter Sefton ***@***.***>, Author ***@***.***>
Subject: Re: [Language-Research-Technology/crate-o] Make sure pcdm hasMember and memberOf have the correct PCDM based URIs and are in the Structure input group (Issue #121)

I kept the https://schema.org/memberOf reference as it exists but http://schema.org/conformsTo does not exist anywhere. Not sure what to replace it with.
For the following invalid locations I replaced them with their location in pcdm.
https://schema.org/hasMember does not exist, changed to pcdm
https://schema.org/fileOf does not exist, changed to pcdm
https://schema.org/hasFile does not exist, changed to pcdm

**Comment by rosanna-smith** [comment]
Merge waiting on some descriptions in this issue: https://github.com/Language-Research-Technology/crate-o/issues/114 @ptsefton

**Comment by otili9890** [comment]
This can be closed after the completion of #114
