### ISSUE TITLE
Bugs from testing RO-Crate creation

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#125]
These are some of the bugs/questions River, Otis and I ran into creating an RO-Crate for the Deafblind corpus (using the mode Language Data Commons top level Collection (corpus):

- [x] @id defaults to ./ - is this something that needs to be edited (add DOI here?) or should that remain as is? Not clear currently.
- [x] Collection Description help text says max 200 word limit, though our description exceeded this and still saved, so assume this is more guidance than a set rule?
- [x] The red property required information icons look more like errors, so even when we'd filled these sections, it seems like there's a problem when there's not. Another colour might be better.
- [x] When creating people, e.g. authors etc. should the ORCID be included in the description or is there another section for this?

**Comment by r-tae** [comment]
Also there's a field 'Citation', the description is "Associated publications". I have a list of publications that reference the corpus, is this the proper place for that?

**Comment by r-tae** [comment]
Re: the organisation lookup

I checked on my local version (up-to-date with `main`), its just the lookup is very slow (on my network at least) and it doesn't cancel in-flight requests if you type more.

You can see in my example that the middle request resolves last and I end up with no monash results.
![CleanShot 2024-05-09 at 11 15 44](https://github.com/Language-Research-Technology/crate-o/assets/22485304/b8136df4-d7b2-4b05-a66a-52833cdf5e7e)

**Comment by rosanna-smith** [comment]
Question about this section @ptsefton: When creating people, e.g. authors etc. should the ORCID be included in the description or is there another section for this?

I checked the language data commons top level and for author we have @id, @type, Name and Description. Should the ORCID go in the description field or in @id? The tooltip for @id just says Uniquie ID, but it's not one of the tooltips I can edit in the mode.

**Comment by ptsefton** [comment]
ORCID if available should go in @id for people

--


From: Rosanna ***@***.***>
Date: Thursday, 16 May 2024 at 11:21 am
To: Language-Research-Technology/crate-o ***@***.***>
Cc: Peter Sefton ***@***.***>, Mention ***@***.***>
Subject: Re: [Language-Research-Technology/crate-o] Bugs from testing RO-Crate creation (Issue #125)

Question about this section @ptsefton<https://github.com/ptsefton>: When creating people, e.g. authors etc. should the ORCID be included in the description or is there another section for this?

I checked the language data commons top level and for author we have @id<https://github.com/id>, @type<https://github.com/type>, Name and Description. Should the ORCID go in the description field or in @id<https://github.com/id>? The tooltip for @id<https://github.com/id> just says Uniquie ID, but it's not one of the tooltips I can edit in the mode.

**Comment by ptsefton** [comment]
We may need to get our own copy of the ROR data and provide a faster lookup

--


From: River ***@***.***>
Date: Thursday, 9 May 2024 at 11:21 am
To: Language-Research-Technology/crate-o ***@***.***>
Cc: Peter Sefton ***@***.***>, Assign ***@***.***>
Subject: Re: [Language-Research-Technology/crate-o] Bugs from testing RO-Crate creation (Issue #125)

Re: the organisation lookup

I checked on my local version (up-to-date with main), its just the lookup is very slow (on my network at least) and it doesn't cancel in-flight requests if you type more.

You can see in my example that the middle request resolves last and I end up with no monash results.
CleanShot.2024-05-09.at.11.15.44.gif (view on web)<https://github.com/Language-Research-Technology/crate-o/assets/22485304/b8136df4-d7b2-4b05-a66a-52833cdf5e7e>

**Comment by ptsefton** [comment]
Yes

--


From: River ***@***.***>
Date: Thursday, 9 May 2024 at 10:57 am
To: Language-Research-Technology/crate-o ***@***.***>
Cc: Peter Sefton ***@***.***>, Assign ***@***.***>
Subject: Re: [Language-Research-Technology/crate-o] Bugs from testing RO-Crate creation (Issue #125)

Also there's a field 'Citation', the description is "Associated publications". I have a list of publications that reference the corpus, is this the proper place for that?

**Comment by r-tae** [comment]
Perfect, thanks @ptsefton ! I believe I have enough to finalise both the Australian Deafblind Signing and Auslan Corpora

**Comment by rosanna-smith** [comment]
Marking as closed since @alvinsw will be updating the description of the @id in Crate-O. (thanks!)
