### ISSUE TITLE
Old metadata file not overwritten by new file

### ISSUE THREAD

**Issue by Supertyp** [Language-Research-Technology/crate-o#126]
When I load an old metadata file and change it in crate-o the old file is not overwritten. When I load the data, the old changes are lost.

**Comment by moisbo** [comment]
Hi @Supertyp Can you add steps so we can reproduce this bug? Also can you send us an ro-crate-metadata.json example file where this happens?
Cheers

**Comment by Supertyp** [comment]
Hi @moisbo, I just recreate the bug but couldn't. It works fine. Maybe it didn't save for some problem in the metadata sheet which is now fixed.

**Comment by moisbo** [comment]
Great, thanks for testing Wolfgang
