### ISSUE TITLE
crate-o content disappears when using bulk-ad 

### ISSUE THREAD

**Issue by Supertyp** [Language-Research-Technology/crate-o#127]
When I load metadata and then use the bulk-ad, some of the existing content e.g. description is lost while other content like id is still there.

**Comment by moisbo** [comment]
Hi @Supertyp can you reproduce this one please? and share with us the ro-crate-metadata.json and the additional-metadata files?

**Comment by Supertyp** [comment]
![Screenshot 2024-05-16 115644](https://github.com/Language-Research-Technology/crate-o/assets/16234553/b68244b2-de2d-4399-84c7-6e15bcbc2846)

When loading the metadata the name of the collection is not shown in the box. The other elements like description, etc. are there.

[ro-crate-metadata.json](https://github.com/Language-Research-Technology/crate-o/files/15333430/ro-crate-metadata.json)

**Comment by Supertyp** [comment]
Here is the additional-metadata file:
[additional-ro-crate-metadata.xlsx](https://github.com/Language-Research-Technology/crate-o/files/15333511/additional-ro-crate-metadata.xlsx)

**Comment by moisbo** [comment]
Is it possible for you to reproduce this in a video, recording your screen while you do it? because we are having trouble repeating this. I have tried with your ro-crate and your additional metadata posted here.
cc: @ptsefton @alvinsw

**Comment by Supertyp** [comment]
[Recording-20240517_102952.webm](https://github.com/Language-Research-Technology/crate-o/assets/16234553/0d178970-8117-4561-b8c0-e3ad79686d97)

Here is the video. The bulk add itself doesn't actualy make the name disapear. but when you click save it is gone.

**Comment by moisbo** [comment]
Oh! its same as River's @r-tae bug https://github.com/Language-Research-Technology/crate-o/issues/129 we will fix in the next push thanks @Supertyp

**Comment by alvinsw** [comment]
Fixed #129
