### ISSUE TITLE
After the RO-Crate is saved, all the filled-in sections return to blank, however clicking in one of these sections fills it again. We also tested it by then saving a copy of the RO-Crate again in that state to see if the JSON file would save as blank but that didn't happen, so just a bug on the UI.

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/crate-o#129]
Hi @r-tae could you provide steps to replicate this bug? And can you add an ro-crate-metadata.json example here please?
Cheers

**Comment by r-tae** [comment]
As far as I can tell it would happen with any crate, I just need to open it and press save to reproduce


https://github.com/Language-Research-Technology/crate-o/assets/22485304/7cd81784-affc-4bed-8f72-45414f55aeef



[ro-crate-metadata.json](https://github.com/Language-Research-Technology/crate-o/files/15328247/ro-crate-metadata.json)

**Comment by alvinsw** [comment]
Fixed
