### ISSUE TITLE
Turn the About.vue into a MarkDown page

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/crate-o#136]
Instead of having an vue program use markdown format and include a file. This is so people can easily edit it. Also remove references from language data commons since this is a general use case software
cc: @ptsefton @alvinsw 

Basically the first bits of the README.md to be included in the markdown.

**Comment by otili9890** [comment]
@moisbo ok I'll do this in my fork

**Comment by moisbo** [comment]
Once you have something working, can you please show us?
