### ISSUE TITLE
Author type not pre-filled on spreadsheet upload

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#142]
I'm working on a spreadsheet template for the bulk add option in Crate-O and came across one question in testing it so far - I've got an author tab similar to the publisher one:

@id | @type	| name
--- | --- | ---
#LDaCA	| Organization |	LDaCA

And an isRef_author field in the root tab to link it to #LDaCA.
When I add it to Crate-O, the author details appear to add fine, including the Organization type, but on the Related People, Orgs & Works tab, the type doesn't pre-fill.
![Screenshot 2024-06-12 at 11 34 53 am](https://github.com/Language-Research-Technology/crate-o/assets/143474414/4b199bb6-f2f6-43a0-b871-2909e18d9e3a)
![Screenshot 2024-06-12 at 11 35 56 am](https://github.com/Language-Research-Technology/crate-o/assets/143474414/ae8c4449-a2e5-4ec7-818f-9c045736d4ea)

Current version of the spreadsheet also attached.
[additional-ro-crate-metadata-template.xlsx](https://github.com/user-attachments/files/15909083/additional-ro-crate-metadata-template.xlsx)

**Comment by ptsefton** [comment]
I am not seeing where the bug is here -- which bit is not pre-filling?

**Comment by rosanna-smith** [comment]
On the first screenshot, type is set to Organization, but on the second screenshot up a level, the type 'choose a type' is blank, unless that's referring to adding a second type?

**Comment by ptsefton** [comment]
That second screen shot is showing a link to LDaCA as the publisher -- the choose a type bit is letting you add another author - either by searching for it or making a new Person or Organization

**Comment by rosanna-smith** [comment]
Ok, got it - in that case maybe the text needs to mention 'another' so it's clear it's to do with a new item and not part of the current author.

**Comment by ptsefton** [comment]
Well it does have a "+" next to it - but lets make that bigger, plz make an issue

**Comment by rosanna-smith** [comment]
Added here https://github.com/Language-Research-Technology/crate-o/issues/149
