### ISSUE TITLE
Add speaker (and all the other ldac: terms) to the People etc tab

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/crate-o#150]
![image](https://github.com/user-attachments/assets/608c9af5-e68a-4bed-95ba-66d18e3ed894)

Speaker & researcher should be in people tab

LinguisticGenre and annotationOf need to go somehwere -- may require some discussion

**Comment by rosanna-smith** [comment]
annotationOf added to Structure, testing linguisticGenre under new Language tab on comprehensive ldac mode
