### ISSUE TITLE
Link to Crate-O user guide on LDaCA site

### ISSUE THREAD

**Issue by benfoley** [Language-Research-Technology/crate-o#151]
Add a link in the help popup to the Crate-O user guide on the LDaCA site.

**Comment by rosanna-smith** [comment]
Reformatted the help so there's less scrolling needed and added a link to the LDACA user guide - suggestions welcome.
Before and after for comparison:
![Screenshot 2024-08-23 at 10 22 18 am](https://github.com/user-attachments/assets/5c5d1235-de90-49f1-81fa-d89984a64c24)
![Screenshot 2024-08-23 at 10 22 25 am](https://github.com/user-attachments/assets/9aeb643e-99ae-42bd-98e1-ad3255e04894)

**Comment by benfoley** [comment]
LGTM
