### ISSUE TITLE
FEATURE: Create  an ro-crate-preview.html inside crate-o on save

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/crate-o#30]
- [ ] Use rochtml as a library and implement it into crate-o
- [ ] Detect if a folder already has an ro-crate-preview.html made by another tool and dont overwrite it
- [ ] make a slider to switch on/off auto-saving preview.html

**Comment by ptsefton** [comment]
Should make this automatic (with an opt out checkbox)

**Comment by moisbo** [comment]
we have this, closing
