### ISSUE TITLE
BUG: Allow datetime range using "/" (ATM this is not accepted)

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/crate-o#49]

**Comment by ptsefton** [comment]
I don't think this is correct:

![image](https://github.com/Language-Research-Technology/crate-o/assets/756184/155af39c-6071-4c11-8472-86531d497856)

The requirement was to allow a "/" separator just for RANGES in ISO dates - not non-ISO dates like YYY/MM/DD. (And it still seems to fail on using the /)

**Comment by moisbo** [comment]
Fix to use moment.8601 in both sides of the string...
and just alert if its incorrect but let people save and continue or add more wrong date formats
