### ISSUE TITLE
Deal with multiple  @type requirements for a profile

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/crate-o#50]
Several issues:

Example:
the root dataset needs to have `RepositoryCollection` and should not allow to change the `Dataset` other ones can be changed

**Comment by ptsefton** [comment]
- On making a new crate with a profile which has multiple root types in the profile, jsut put the types there.

- When the user loads a profile and the crate DOES NOT match the required root types put a message near the top of the page, as suggested by @alvinsw "This crate does not have the required ROOT datatypes" with a button to add types that are not already there.

**Comment by ptsefton** [comment]
Fixed this in latest update -- can probably use the same technique for conformsTo URLs

**Comment by moisbo** [comment]
re-opening because I think we didnt add it to when creating a crate from scratch cc: @alex-ip
