### ISSUE TITLE
BUG: in ComputationalTool profile, input and output are added in broken way

### ISSUE THREAD

**Issue by ptsefton** [Language-Research-Technology/crate-o#55]
First time you add an "input" it gets added with "input" as a property but the SECOND time it gets added with a URI for the property key:

```
  "@graph": [
    {
      "@id": "./",
      "@type": [
        "Dataset",
        "ComputationalTool"
      ],
      "input": {
        "@id": "http://json.com"
      },
      "https://discovery.biothings.io/view/bioschemas/input": {
        "@id": "#undefined-input-1"
      }
    },

```

![image](https://github.com/Language-Research-Technology/crate-o/assets/756184/e2022ea1-cbfa-4d61-8a5b-6d40b542d2f3)

**Comment by moisbo** [comment]
The fix for this is to change the way inputs are specified in the layout to use a full URI rather than the shortName

**Comment by ptsefton** [comment]
We're leaving this approach behind us.
