### ISSUE TITLE
Tooltip icons missing for some metadata

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#76]
These metadata items are missing the tooltip icon, even though some do have help text in the code:

- @id
- @name
- Conforms To
- Is Accessible For Free
- Language

Side note on Language - this appears twice under Others, but it's not clear how they differ, and they're separated by Date Created which is confusing if they should be considered together. (There's another dropdown for language with text, number and entity, but these aren't explained).

**Comment by moisbo** [comment]
I'll fix @id and @type which has to be written in crate-o the other issue goes on the [ro-crate-editor-profiles ](https://github.com/Language-Research-Technology/ro-crate-editor-profiles) repo (I think)

**Comment by moisbo** [comment]
Oh actually, what text should be on @id and @type help ?

**Comment by rosanna-smith** [comment]
Maria mentioned that ID might be auto-generated and not something the user needs to provide values for, so maybe there's a wider question here on whether this should be hidden to avoid confusion. Possibly a similar question for type?
