### ISSUE TITLE
Show required fields for a given profile

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#77]
Would we be able to add functionality to show which fields in a given profile are mandatory/required and which are optional? This would probably make it clearer to new users what essentials are needed when adding data.

- [x] Show on screen
- [x] When you save, show an info box at the top or modal that list the required
- [x] Move the save button outside of the menu

**Comment by weaver-m** [comment]
Proposed compulsory metadata for Crate-O 'Language Data Commons top level Collection (corpus)' profile:
1. ID  -- @moisbo Pt said that @id is where the collection PID (e.g. DOI) should go, please confirm
2. Name [of the  collection]
3.  Description 
4.  Language
5.  Author /Creator/Compiler/Collector
6. Publisher

**Comment by moisbo** [comment]
yes
