### ISSUE TITLE
Should suppress redundant context entries for "@type" and "@id"

### ISSUE THREAD

**Issue by alex-ip** [Language-Research-Technology/crate-o#80]
When creating & editing a new ro-crate-metadata.json file with Crate-O, we wind up with the following context section:
`  "@context": [
    "https://w3id.org/ro/crate/1.1/context",
    {
      "@vocab": "http://schema.org/"
    },
    {
      "@type": "@type"
    },
    {
      "@id": "@id"
    }
  ],
`

It would appear that we have redundant context entries for "@type" and "@id".

This is more a cosmetic issue than anything else, but we probably want to make sure that we don't see this kind of entry.

**Comment by moisbo** [comment]
Hi Alex -- can you help me to show me how to reproduce this? I am not able to by just creating and editing a new ro crate

**Comment by moisbo** [comment]
Hi @alex-ip can you please test this again?

**Comment by moisbo** [comment]
Alex tested and cannot reproduce
