### ISSUE TITLE
Abort Error

### ISSUE THREAD

**Issue by rosanna-smith** [Language-Research-Technology/crate-o#85]
If I go to Open Directory, but then decide to cancel/close the request, I now get the following AbortError:
![AbortError](https://github.com/Language-Research-Technology/crate-o/assets/143474414/e6e6e8ea-e084-482f-94a5-6503776cdca6)
This is probably just confirming I've cancelled, but is probably redundant.

**Comment by moisbo** [comment]
We dont think we can do anything about this, because its handled by the browser
