### ISSUE TITLE
Bug: small window sizes make it impossible to set profile

### ISSUE THREAD

**Issue by r-tae** [Language-Research-Technology/crate-o#88]
When the profile dropdown overflows into the `. . .` menu, the menu automatically closes when you try to mouse over the profile dropdown.

Attached screen recording shows behaviour (I am not selecting any profile, there isn't enough time to)

https://github.com/Language-Research-Technology/crate-o/assets/22485304/6517a29e-c8a8-4270-80f4-52fe64624c4d

**Comment by moisbo** [comment]
Thanks River. We'll have a look
